name: bpe
description: Fast tokenizer for CL100kBase and O2O100kBase. Streaming count estimators 
version: 1.0.0
repository: https://github.com/ArcaneArts/bpe
environment:
  sdk: ^3.7.0
dependencies:
  characters: ^1.4.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
